### ISSUE TITLE
Not a valid error URL prompts in console upon downloading despite being a valid URL.

### ISSUE THREAD

**Issue by iamnotbobby** [o7q/MediaDownloader#9]
**Describe the bug**
Not a valid error URL prompts in console upon downloading despite being a valid URL. I've used MediaDownloader before hand and it has downloaded the same domains/links (tiktok/youtube/etc).

**To Reproduce**
1. Go to MediaDownloader
2. Download a video from Youtube.
4. See error in console.

**Expected behavior**
The video to download.

**Screenshots**
![15735](https://user-images.githubusercontent.com/107429396/217437866-f6c27490-965a-4c62-a40c-7c67c9d7410e.png)

**Comment by iamnotbobby** [comment]
My apologies. Looks like it was fixed in the latest release that was released while I was typing this. Sorry for the bother!

**Comment by o7q** [comment]
Actually that bug is not the one I fixed. Unsure on what is causing that, the bug fix I just released was for something else.

**Comment by o7q** [comment]
Did you accidently put a space before the URL?

**Comment by iamnotbobby** [comment]
Putting a space before the URL as well as after still continues as normal. I downloaded the new version, removed the "mediadownloader" folder and replaced it with the new "mediadownloader" folder. Intitially, I would just drag and drop the files within the "mediadownloader" folder in the .zip into my "mediadownloader" folder and it would replace the ones in the intitial folder. I solved this by deleting the "mediadownloader" folder and completely extracting the .zip. I assume there were either missing or corrupted files within the folder. 

I didn't bother looking at the commits history so I assume it was a bug you fixed, but here you go for the solution.

**Comment by iamnotbobby** [comment]
![image](https://user-images.githubusercontent.com/107429396/217440434-f88ca7eb-8ee3-4d9c-bdc0-7bd6515228ec.png)
![image](https://user-images.githubusercontent.com/107429396/217440441-e6acd83c-6a6c-44da-ae1d-dfecd196ca08.png)

**Comment by o7q** [comment]
Yeah, ensure you always use the latest `mediadownloader` folder when you download a new version.

**Comment by iamnotbobby** [comment]
> Yeah, ensure you always use the latest `mediadownloader` folder when you download a new version.

Actually. Looks like I need to reopen this bug report. I did some further testing. I replaced everything via extracting the .zip, downloaded, and re-downloaded using the same link. Downloading another video generated the same bug as reported above. This bug can be fixed by extracting the .zip completely, but will continue to generate the same error once you decide to download another video.

**Comment by o7q** [comment]
Strange. I have never seen this error. I will look into it tomorrow.

**Comment by o7q** [comment]
It works when I try that URL. Could you send a picture of what you are using for settings in MediaDownloader?

**Comment by iamnotbobby** [comment]
Had it no other settings set other than the format on what the output video is. When trying it on another computer, I can download other videos successfully. I'll investigate further when I get home. It appears to be an issue with my computer. I noticed the \x7f unicode in the error in the initial screenshot. Bit odd.

**Comment by o7q** [comment]
It may be related to Windows 11. I have not fully tested it on that version.

**Comment by o7q** [comment]
Try this as a check:
- Attempt to download the URL that was not working
- Do not close MediaDownloader as this will clear the file. After it fails to download send the `md.bat` file that is located inside the `mediadownloader` folder. That file should give a lot of information about what the issue could be.
![Untitled](https://user-images.githubusercontent.com/103224608/217657456-13b3b0c7-c62d-4670-83b0-76f5f2fe528d.png)

**Comment by iamnotbobby** [comment]
Alright, so I looked into the md.bat file and I saw the unicode as mentioned before. I did some further testing and could produce a consistent result that would result in the unicode showing in the URL box. I somehow did not see this last night.

I produced this consistent result by doing ctrl + a then backspace in a millisecond timeframe. As far as I'm aware, this keyboard combination would not insert that unicode in specific.


https://user-images.githubusercontent.com/107429396/217725192-91e205e1-e33a-41c7-bc2e-71a749981b80.mp4

Here's the md.bat in question:

![image](https://user-images.githubusercontent.com/107429396/217725936-7a45f2d5-9859-46b3-9d34-f50b2fcd7b1c.png)

**Comment by o7q** [comment]
Yeah that delete character is a weird thing I've noticed, it's a Windows thing and has nothing to do with MediaDownloader. Also you are naming the video "-". I don't think that's a problem but I would just leave it blank or give it a name. Does the download work after removing the weird character?

**Comment by o7q** [comment]
Tomorrow if I remember I'll roll out an update that checks to see if that character exists and removes it.

**Comment by iamnotbobby** [comment]
When changing the output file name, it does not affect anything. 

Yes, after removing the unicode, the program continues as normal but will still generate that same unicode.

**Comment by o7q** [comment]
I was able to recreate the error. Working on the fix now.
![Screenshot 2023-02-09 105905](https://user-images.githubusercontent.com/103224608/217884675-9e543c44-0425-4660-9ea3-c8d093caad27.png)

**Comment by o7q** [comment]
The character is created when you do CTRL + Backspace.

**Comment by iamnotbobby** [comment]
> The character is created when you do CTRL + Backspace.

Just looked up this key combination and looks like it was previously present in other applications like Notepad.

**Comment by o7q** [comment]
I released the new version containing the [fix](https://github.com/o7q/MediaDownloader/commit/80601e88650e922cdb1e1d47dec6503dfbeebe74#r100025374).
https://github.com/o7q/MediaDownloader/releases/tag/v3.8.5.0

**Comment by iamnotbobby** [comment]
> I released the new version containing the [fix](https://github.com/o7q/MediaDownloader/commit/80601e88650e922cdb1e1d47dec6503dfbeebe74#r100025374). https://github.com/o7q/MediaDownloader/releases/tag/v3.8.5.0

Fix works as intended. Thank you.
